# Reference this view as code_hdr_values
schema: public

dimensions:
  code_name: {}
  value_name: {}
  value: {}
  is_active: {}
  created_at: {}
  created_by: {}
  updated_at: {}
  updated_by: {}

  id:
    format: ID
    primary_key: true

measures:
  count:
    aggregate_type: count
